{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/dedalus-project/dedalus.json"}, "html": {"href": "#!/dedalus-project/dedalus"}, "avatar": {"href": "data/bytebucket.org/ravatar/{1dc39ab6-2798-450d-af2f-e976f94b5794}ts=2009435"}}, "type": "repository", "name": "dedalus", "full_name": "dedalus-project/dedalus", "uuid": "{1dc39ab6-2798-450d-af2f-e976f94b5794}"}, "links": {"attachments": {"href": "data/repositories/dedalus-project/dedalus/issues/22/attachments_page=1.json"}, "self": {"href": "data/repositories/dedalus-project/dedalus/issues/22.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/dedalus-project/dedalus/issues/22/watch"}, "comments": {"href": "data/repositories/dedalus-project/dedalus/issues/22/comments_page=1.json"}, "html": {"href": "#!/dedalus-project/dedalus/issues/22/intel-build-environment-squashing-locale"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/dedalus-project/dedalus/issues/22/vote"}}, "reporter": {"display_name": "Max Hutchinson", "uuid": "{c3ee6db9-a2d0-4ec7-a528-daab6d351f6c}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bc3ee6db9-a2d0-4ec7-a528-daab6d351f6c%7D"}, "html": {"href": "https://bitbucket.org/%7Bc3ee6db9-a2d0-4ec7-a528-daab6d351f6c%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/5509648ce6ebfb0953dee9f5977a552fd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsMH-4.png"}}, "nickname": "maxhutch", "type": "user", "account_id": "557058:e9911fad-4396-40a7-b4be-620f25fbec30"}, "title": "Intel build environment squashing locale settings", "component": null, "votes": 0, "watches": 1, "content": {"raw": "I'm trying to build on my workstation and can't get past this issue:\r\n\r\n```\r\n#!bash\r\n\r\nicc: command line warning #10006: ignoring unknown option '-fwrapv'\r\nCatastrophic error: could not set locale \"\" to allow processing of multibyte characters\r\n\r\n```\r\n\r\nWhich is weird, because if I manually execute the offending compile command, it throws some warnings but completes compilation.  I've included both commands below.\r\n\r\nIt seems like the python compile environment is suppressing the LANG environment variable, which [others have pointed to](https://software.intel.com/en-us/articles/cdiag912) as the source of this type of error.  In my shell, it is set:\r\n```\r\n\r\nmaxhutch@edoras:~/src/dedalus2$ env | grep LANG\r\nLANG=en_US.UTF-8\r\n\r\n```\r\n\r\n### Configuration ###\r\n * Debian Wheezy\r\n * Intel 14.0.1\r\n * Fresh (today) anaconda3 environment, with only dedalus installation directions followed\r\n * OpenMPI 1.6.5\r\n\r\n\r\n\r\n```\r\n#!bash\r\n\r\nmaxhutch@edoras:~/src/dedalus2$ ~/anaconda3/bin/python3 setup.py build_ext --inplaceLooking for fftw prefix\r\n  Found env var FFTW_PATH = /opt/fftw3/\r\nLooking for mpi prefix\r\n  Found env var MPI_PATH = /opt/openmpi/\r\nLooking for fftw prefix\r\n  Found env var FFTW_PATH = /opt/fftw3/\r\nrunning build_ext\r\nbuilding 'dedalus2.libraries.fftw.fftw_wrappers' extension\r\nicc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Idedalus2/libraries/fftw/ -I/home/maxhutch/anaconda3/lib/python3.4/site-packages/numpy/core/include -I/home/maxhutch/anaconda3/lib/python3.4/site-packages/mpi4py/include -I/opt/fftw3/include -I/opt/openmpi/include -I/home/maxhutch/anaconda3/include/python3.4m -c dedalus2/libraries/fftw/fftw_wrappers.c -o build/temp.linux-x86_64-3.4/dedalus2/libraries/fftw/fftw_wrappers.o\r\nicc: command line warning #10006: ignoring unknown option '-fwrapv'\r\nCatastrophic error: could not set locale \"\" to allow processing of multibyte characters\r\n\r\ncompilation aborted for dedalus2/libraries/fftw/fftw_wrappers.c (code 4)\r\nerror: command 'icc' failed with exit status 4\r\nmaxhutch@edoras:~/src/dedalus2$ icc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Idedalus2/libraries/fftw/ -I/home/maxhutch/anaconda3/lib/python3.4/site-packages/numpy/core/include -I/home/maxhutch/anaconda3/lib/python3.4/site-packages/mpi4py/include -I/opt/fftw3/include -I/opt/openmpi/include -I/home/maxhutch/anaconda3/include/python3.4m -c dedalus2/libraries/fftw/fftw_wrappers.c -o build/temp.linux-x86_64-3.4/dedalus2/libraries/fftw/fftw_wrappers.o\r\nicc: command line warning #10006: ignoring unknown option '-fwrapv'\r\nIn file included from /home/maxhutch/anaconda3/lib/python3.4/site-packages/numpy/core/include/numpy/ndarraytypes.h(1804),\r\n                 from /home/maxhutch/anaconda3/lib/python3.4/site-packages/numpy/core/include/numpy/ndarrayobject.h(17),\r\n                 from /home/maxhutch/anaconda3/lib/python3.4/site-packages/numpy/core/include/numpy/arrayobject.h(4),\r\n                 from dedalus2/libraries/fftw/fftw_wrappers.c(232):\r\n/home/maxhutch/anaconda3/lib/python3.4/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h(15): warning #1224: #warning directive: \"Using deprecated NumPy API, disable it by \"          \"#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION\"\r\n  #warning \"Using deprecated NumPy API, disable it by \" \\\r\n   ^\r\n\r\ndedalus2/libraries/fftw/fftw_wrappers.c(6509): warning #167: argument of type \"int *\" is incompatible with parameter of type \"const fftw_r2r_kind={enum fftw_r2r_kind_do_not_use_me} *\"\r\n    __pyx_v_self->forward_plan = fftw_plan_guru_r2r(__pyx_v_trans_rank, __pyx_v_trans_struct, __pyx_v_vec_rank, __pyx_v_vec_struct_f, __pyx_v_gdata, __pyx_v_cdata, __pyx_v_kind, (__pyx_v_intflags | __pyx_e_8dedalus2_9libraries_4fftw_10fftw_c_api_FFTW_DESTROY_INPUT));\r\n                                                                                                                                                                    ^\r\n\r\ndedalus2/libraries/fftw/fftw_wrappers.c(6518): warning #167: argument of type \"int *\" is incompatible with parameter of type \"const fftw_r2r_kind={enum fftw_r2r_kind_do_not_use_me} *\"\r\n    __pyx_v_self->backward_plan = fftw_plan_guru_r2r(__pyx_v_trans_rank, __pyx_v_trans_struct, __pyx_v_vec_rank, __pyx_v_vec_struct_b, __pyx_v_cdata, __pyx_v_gdata, __pyx_v_kind, (__pyx_v_intflags | __pyx_e_8dedalus2_9libraries_4fftw_10fftw_c_api_FFTW_DESTROY_INPUT));\r\n                                                                                                                                                                     ^\r\n\r\ndedalus2/libraries/fftw/fftw_wrappers.c(8016): warning #167: argument of type \"int *\" is incompatible with parameter of type \"const fftw_r2r_kind={enum fftw_r2r_kind_do_not_use_me} *\"\r\n    __pyx_v_self->forward_plan = fftw_plan_guru_r2r(__pyx_v_trans_rank, __pyx_v_trans_struct, __pyx_v_vec_rank, __pyx_v_vec_struct_f, __pyx_v_gdata, __pyx_v_cdata, __pyx_v_kind, (__pyx_v_intflags | __pyx_e_8dedalus2_9libraries_4fftw_10fftw_c_api_FFTW_DESTROY_INPUT));\r\n                                                                                                                                                                    ^\r\n\r\ndedalus2/libraries/fftw/fftw_wrappers.c(8025): warning #167: argument of type \"int *\" is incompatible with parameter of type \"const fftw_r2r_kind={enum fftw_r2r_kind_do_not_use_me} *\"\r\n    __pyx_v_self->backward_plan = fftw_plan_guru_r2r(__pyx_v_trans_rank, __pyx_v_trans_struct, __pyx_v_vec_rank, __pyx_v_vec_struct_b, __pyx_v_cdata, __pyx_v_gdata, __pyx_v_kind, (__pyx_v_intflags | __pyx_e_8dedalus2_9libraries_4fftw_10fftw_c_api_FFTW_DESTROY_INPUT));\r\n                                                                                                                                                                     ^\r\n\r\nmaxhutch@edoras:~/src/dedalus2$ \r\n```", "markup": "markdown", "html": "<p>I'm trying to build on my workstation and can't get past this issue:</p>\n<div class=\"codehilite language-bash\"><pre><span></span>icc: <span class=\"nb\">command</span> line warning <span class=\"c1\">#10006: ignoring unknown option &#39;-fwrapv&#39;</span>\nCatastrophic error: could not <span class=\"nb\">set</span> locale <span class=\"s2\">&quot;&quot;</span> to allow processing of multibyte characters\n</pre></div>\n\n\n<p>Which is weird, because if I manually execute the offending compile command, it throws some warnings but completes compilation.  I've included both commands below.</p>\n<p>It seems like the python compile environment is suppressing the LANG environment variable, which <a data-is-external-link=\"true\" href=\"https://software.intel.com/en-us/articles/cdiag912\" rel=\"nofollow\">others have pointed to</a> as the source of this type of error.  In my shell, it is set:</p>\n<div class=\"codehilite\"><pre><span></span>maxhutch@edoras:~/src/dedalus2$ env | grep LANG\nLANG=en_US.UTF-8\n</pre></div>\n\n\n<h3 id=\"markdown-header-configuration\">Configuration</h3>\n<ul>\n<li>Debian Wheezy</li>\n<li>Intel 14.0.1</li>\n<li>Fresh (today) anaconda3 environment, with only dedalus installation directions followed</li>\n<li>OpenMPI 1.6.5</li>\n</ul>\n<div class=\"codehilite language-bash\"><pre><span></span>maxhutch@edoras:~/src/dedalus2$ ~/anaconda3/bin/python3 setup.py build_ext --inplaceLooking <span class=\"k\">for</span> fftw prefix\n  Found env var <span class=\"nv\">FFTW_PATH</span> <span class=\"o\">=</span> /opt/fftw3/\nLooking <span class=\"k\">for</span> mpi prefix\n  Found env var <span class=\"nv\">MPI_PATH</span> <span class=\"o\">=</span> /opt/openmpi/\nLooking <span class=\"k\">for</span> fftw prefix\n  Found env var <span class=\"nv\">FFTW_PATH</span> <span class=\"o\">=</span> /opt/fftw3/\nrunning build_ext\nbuilding <span class=\"s1\">&#39;dedalus2.libraries.fftw.fftw_wrappers&#39;</span> extension\nicc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Idedalus2/libraries/fftw/ -I/home/maxhutch/anaconda3/lib/python3.4/site-packages/numpy/core/include -I/home/maxhutch/anaconda3/lib/python3.4/site-packages/mpi4py/include -I/opt/fftw3/include -I/opt/openmpi/include -I/home/maxhutch/anaconda3/include/python3.4m -c dedalus2/libraries/fftw/fftw_wrappers.c -o build/temp.linux-x86_64-3.4/dedalus2/libraries/fftw/fftw_wrappers.o\nicc: <span class=\"nb\">command</span> line warning <span class=\"c1\">#10006: ignoring unknown option &#39;-fwrapv&#39;</span>\nCatastrophic error: could not <span class=\"nb\">set</span> locale <span class=\"s2\">&quot;&quot;</span> to allow processing of multibyte characters\n\ncompilation aborted <span class=\"k\">for</span> dedalus2/libraries/fftw/fftw_wrappers.c <span class=\"o\">(</span>code <span class=\"m\">4</span><span class=\"o\">)</span>\nerror: <span class=\"nb\">command</span> <span class=\"s1\">&#39;icc&#39;</span> failed with <span class=\"nb\">exit</span> status <span class=\"m\">4</span>\nmaxhutch@edoras:~/src/dedalus2$ icc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Idedalus2/libraries/fftw/ -I/home/maxhutch/anaconda3/lib/python3.4/site-packages/numpy/core/include -I/home/maxhutch/anaconda3/lib/python3.4/site-packages/mpi4py/include -I/opt/fftw3/include -I/opt/openmpi/include -I/home/maxhutch/anaconda3/include/python3.4m -c dedalus2/libraries/fftw/fftw_wrappers.c -o build/temp.linux-x86_64-3.4/dedalus2/libraries/fftw/fftw_wrappers.o\nicc: <span class=\"nb\">command</span> line warning <span class=\"c1\">#10006: ignoring unknown option &#39;-fwrapv&#39;</span>\nIn file included from /home/maxhutch/anaconda3/lib/python3.4/site-packages/numpy/core/include/numpy/ndarraytypes.h<span class=\"o\">(</span><span class=\"m\">1804</span><span class=\"o\">)</span>,\n                 from /home/maxhutch/anaconda3/lib/python3.4/site-packages/numpy/core/include/numpy/ndarrayobject.h<span class=\"o\">(</span><span class=\"m\">17</span><span class=\"o\">)</span>,\n                 from /home/maxhutch/anaconda3/lib/python3.4/site-packages/numpy/core/include/numpy/arrayobject.h<span class=\"o\">(</span><span class=\"m\">4</span><span class=\"o\">)</span>,\n                 from dedalus2/libraries/fftw/fftw_wrappers.c<span class=\"o\">(</span><span class=\"m\">232</span><span class=\"o\">)</span>:\n/home/maxhutch/anaconda3/lib/python3.4/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h<span class=\"o\">(</span><span class=\"m\">15</span><span class=\"o\">)</span>: warning <span class=\"c1\">#1224: #warning directive: &quot;Using deprecated NumPy API, disable it by &quot;          &quot;#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION&quot;</span>\n  <span class=\"c1\">#warning &quot;Using deprecated NumPy API, disable it by &quot; \\</span>\n   ^\n\ndedalus2/libraries/fftw/fftw_wrappers.c<span class=\"o\">(</span><span class=\"m\">6509</span><span class=\"o\">)</span>: warning <span class=\"c1\">#167: argument of type &quot;int *&quot; is incompatible with parameter of type &quot;const fftw_r2r_kind={enum fftw_r2r_kind_do_not_use_me} *&quot;</span>\n    __pyx_v_self-&gt;forward_plan <span class=\"o\">=</span> fftw_plan_guru_r2r<span class=\"o\">(</span>__pyx_v_trans_rank, __pyx_v_trans_struct, __pyx_v_vec_rank, __pyx_v_vec_struct_f, __pyx_v_gdata, __pyx_v_cdata, __pyx_v_kind, <span class=\"o\">(</span>__pyx_v_intflags <span class=\"p\">|</span> __pyx_e_8dedalus2_9libraries_4fftw_10fftw_c_api_FFTW_DESTROY_INPUT<span class=\"o\">))</span><span class=\"p\">;</span>\n                                                                                                                                                                    ^\n\ndedalus2/libraries/fftw/fftw_wrappers.c<span class=\"o\">(</span><span class=\"m\">6518</span><span class=\"o\">)</span>: warning <span class=\"c1\">#167: argument of type &quot;int *&quot; is incompatible with parameter of type &quot;const fftw_r2r_kind={enum fftw_r2r_kind_do_not_use_me} *&quot;</span>\n    __pyx_v_self-&gt;backward_plan <span class=\"o\">=</span> fftw_plan_guru_r2r<span class=\"o\">(</span>__pyx_v_trans_rank, __pyx_v_trans_struct, __pyx_v_vec_rank, __pyx_v_vec_struct_b, __pyx_v_cdata, __pyx_v_gdata, __pyx_v_kind, <span class=\"o\">(</span>__pyx_v_intflags <span class=\"p\">|</span> __pyx_e_8dedalus2_9libraries_4fftw_10fftw_c_api_FFTW_DESTROY_INPUT<span class=\"o\">))</span><span class=\"p\">;</span>\n                                                                                                                                                                     ^\n\ndedalus2/libraries/fftw/fftw_wrappers.c<span class=\"o\">(</span><span class=\"m\">8016</span><span class=\"o\">)</span>: warning <span class=\"c1\">#167: argument of type &quot;int *&quot; is incompatible with parameter of type &quot;const fftw_r2r_kind={enum fftw_r2r_kind_do_not_use_me} *&quot;</span>\n    __pyx_v_self-&gt;forward_plan <span class=\"o\">=</span> fftw_plan_guru_r2r<span class=\"o\">(</span>__pyx_v_trans_rank, __pyx_v_trans_struct, __pyx_v_vec_rank, __pyx_v_vec_struct_f, __pyx_v_gdata, __pyx_v_cdata, __pyx_v_kind, <span class=\"o\">(</span>__pyx_v_intflags <span class=\"p\">|</span> __pyx_e_8dedalus2_9libraries_4fftw_10fftw_c_api_FFTW_DESTROY_INPUT<span class=\"o\">))</span><span class=\"p\">;</span>\n                                                                                                                                                                    ^\n\ndedalus2/libraries/fftw/fftw_wrappers.c<span class=\"o\">(</span><span class=\"m\">8025</span><span class=\"o\">)</span>: warning <span class=\"c1\">#167: argument of type &quot;int *&quot; is incompatible with parameter of type &quot;const fftw_r2r_kind={enum fftw_r2r_kind_do_not_use_me} *&quot;</span>\n    __pyx_v_self-&gt;backward_plan <span class=\"o\">=</span> fftw_plan_guru_r2r<span class=\"o\">(</span>__pyx_v_trans_rank, __pyx_v_trans_struct, __pyx_v_vec_rank, __pyx_v_vec_struct_b, __pyx_v_cdata, __pyx_v_gdata, __pyx_v_kind, <span class=\"o\">(</span>__pyx_v_intflags <span class=\"p\">|</span> __pyx_e_8dedalus2_9libraries_4fftw_10fftw_c_api_FFTW_DESTROY_INPUT<span class=\"o\">))</span><span class=\"p\">;</span>\n                                                                                                                                                                     ^\n\nmaxhutch@edoras:~/src/dedalus2$ \n</pre></div>", "type": "rendered"}, "assignee": null, "state": "closed", "version": null, "edited_on": null, "created_on": "2015-02-06T15:44:48.050973+00:00", "milestone": null, "updated_on": "2018-10-30T21:16:45.730475+00:00", "type": "issue", "id": 22}