{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/dedalus-project/dedalus.json"}, "html": {"href": "#!/dedalus-project/dedalus"}, "avatar": {"href": "data/bytebucket.org/ravatar/{1dc39ab6-2798-450d-af2f-e976f94b5794}ts=2009435"}}, "type": "repository", "name": "dedalus", "full_name": "dedalus-project/dedalus", "uuid": "{1dc39ab6-2798-450d-af2f-e976f94b5794}"}, "links": {"attachments": {"href": "data/repositories/dedalus-project/dedalus/issues/43/attachments_page=1.json"}, "self": {"href": "data/repositories/dedalus-project/dedalus/issues/43.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/dedalus-project/dedalus/issues/43/watch"}, "comments": {"href": "data/repositories/dedalus-project/dedalus/issues/43/comments_page=1.json"}, "html": {"href": "#!/dedalus-project/dedalus/issues/43/flowtoolscflcompute_dt-returning"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/dedalus-project/dedalus/issues/43/vote"}}, "reporter": {"display_name": "Benjamin Brown", "uuid": "{7ccecdb3-3639-4001-8249-060e80320bda}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B7ccecdb3-3639-4001-8249-060e80320bda%7D"}, "html": {"href": "https://bitbucket.org/%7B7ccecdb3-3639-4001-8249-060e80320bda%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:0696c4b9-e94c-41ac-82be-62ad4f0ec571/8bc6f4da-871a-48b1-88ea-998663d18142/128"}}, "nickname": "Benjamin Brown", "type": "user", "account_id": "557058:0696c4b9-e94c-41ac-82be-62ad4f0ec571"}, "title": "flowtools.CFL.compute_dt() returning AttributeError when cadence=1", "component": null, "votes": 0, "watches": 1, "content": {"raw": "Commit 543424f0c61d appears to break flowtools.CFL.compute_dt() when the CFL cadence=1.  To reproduce this, edit dedalus/examples/ivp/2d_rayleigh_benard.py and change cadence=1, then run the script.  \r\n\r\nDoing so will reproduce the following error:\r\n\r\n    Traceback (most recent call last):\r\n      File \"rayleigh_benard.py\", line 111, in <module>\r\n        dt = CFL.compute_dt()\r\n      File \"/home5/bpbrown/dedalus/src/dedalus/dedalus/extras/flow_tools.py\", line 203, in compute_dt\r\n        max_global_freq = self.reducer.global_max(local_freqs)\r\n      File \"/home5/bpbrown/dedalus/src/dedalus/dedalus/extras/flow_tools.py\", line 51, in global_max\r\n        if data.size:\r\n    AttributeError: 'int' object has no attribute 'size'\r\n\r\nThis error does not occur when CFL cadence>1.\r\n\r\n\r\nCommit 3c591a74b7d2 has the correct expected behaviour for CFL compute_dt().", "markup": "markdown", "html": "<p>Commit <a href=\"#!/dedalus-project/dedalus/commits/543424f0c61d\" rel=\"nofollow\" class=\"ap-connect-link\">543424f0c61d</a> appears to break flowtools.CFL.compute_dt() when the CFL cadence=1.  To reproduce this, edit dedalus/examples/ivp/2d_rayleigh_benard.py and change cadence=1, then run the script.  </p>\n<p>Doing so will reproduce the following error:</p>\n<div class=\"codehilite\"><pre><span></span>Traceback (most recent call last):\n  File &quot;rayleigh_benard.py&quot;, line 111, in &lt;module&gt;\n    dt = CFL.compute_dt()\n  File &quot;/home5/bpbrown/dedalus/src/dedalus/dedalus/extras/flow_tools.py&quot;, line 203, in compute_dt\n    max_global_freq = self.reducer.global_max(local_freqs)\n  File &quot;/home5/bpbrown/dedalus/src/dedalus/dedalus/extras/flow_tools.py&quot;, line 51, in global_max\n    if data.size:\nAttributeError: &#39;int&#39; object has no attribute &#39;size&#39;\n</pre></div>\n\n\n<p>This error does not occur when CFL cadence&gt;1.</p>\n<p>Commit <a href=\"#!/dedalus-project/dedalus/commits/3c591a74b7d2\" rel=\"nofollow\" class=\"ap-connect-link\">3c591a74b7d2</a> has the correct expected behaviour for CFL compute_dt().</p>", "type": "rendered"}, "assignee": null, "state": "resolved", "version": null, "edited_on": null, "created_on": "2018-07-15T14:23:35.869519+00:00", "milestone": null, "updated_on": "2018-07-20T14:10:12.183971+00:00", "type": "issue", "id": 43}